[package]
name = "trenino"
version = "0.7.3"
description = "trenino - Bridge hardware to Train Sim World"
authors = ["Alberto Restifo"]
license = "CC-BY-NC-4.0"
repository = "https://github.com/albertorestifo/trenino"
edition = "2021"

[package.metadata.vjoy]
version = "2.2.2.0"
release = "https://github.com/BrunnerInnovation/vJoy/releases/tag/v2.2.2.0"
installer-sha256 = "ef569a3105cd301b89580f18f60c66b339e95296acf2c0dfcaf4b4bbf8ab68fe"
sdk-sha256 = "0e796b185b66819d5fbeae645f3f038ecbfbbde837d3d3f06cba82ae1db07c67"

[lib]
name = "trenino_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["webview-data-url"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tokio = { version = "1", features = ["time"] }
reqwest = { version = "0.13", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
